import NextAuthProvider from './components/NextAuthProvider';
import Header from './components/Header'
import Footer from './components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className="flex h-full flex-col">
        <NextAuthProvider>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
